services:

  db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-projeto}
      MYSQL_DATABASE: ${DATABASE_NAME:-projeto}
      MYSQL_USER: ${USER:-projeto}
      MYSQL_PASSWORD: ${PASSWORD:-projeto}
    ports:
      - "3306:3306"

  api:
    image: lucasouzamil/projeto-api-consulta-dolar:v1.0
    environment:
      # Informações da conectividade com o DB
      - USER=${USER:-projeto}
      - PASSWORD=${PASSWORD:-projeto}
      - SERVER=db
      - PORT=3306
      - DATABASE_NAME=${DATABASE_NAME:-projeto}
      # Informações da JWT
      - SECRET_KEY=${SECRET_KEY:-key_super_secreta}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always